### ISSUE TITLE
too many nodes detected

### ISSUE THREAD

**Issue by SwissalpS** [SwissalpS/replacer#10]
When replacer finds more nodes than are in inventory, those it can place are placed.
But when it finds too many nodes for limit, it does nothing.
I feel it should do the same in both cases, either just warn or place up to limit.
Thoughts?

**Comment by thomasrudin** [comment]
>  I feel it should do the same in both cases, either just warn or place up to limit.

Sounds good, if possible... :+1:

**Comment by SwissalpS** [comment]
[fixed](https://github.com/SwissalpS/replacer/tree/bffc5d3596fa1f48a90257ca9ff08efaf7eeb550)
not yet merged to master
