### ISSUE TITLE
tool workshop 'repairs' replacer

### ISSUE THREAD

**Issue by SwissalpS** [SwissalpS/replacer#12]
This is confusing and needs to be fixed so that tool workshop does not change tool but spits it out like it does with anything it can't repair.

**Comment by HybridDog** [comment]
Maybe you need to register the replacer as item instead of tool.
https://github.com/SwissalpS/replacer/blob/7fdd94e9f1d8fa443d53129305555660297aae87/replacer.lua#L507

**Comment by SwissalpS** [comment]
no that's correct. I added the issue without trying myself. Seems like this guy wanted to troll me.

so sorry for the false alarm.
