### ISSUE TITLE
Usage limits for crust mode

### ISSUE THREAD

**Issue by 6r1d** [SwissalpS/replacer#13]
I wonder if it's possible to add usage limits like a digtron has: something like "no more than `x` blocks at `y` seconds".
My reason is that players notice when others use the replacer.
It might also allow to use food in time.

**Comment by HybridDog** [comment]
You can reduce the replacer.max_nodes setting.
https://github.com/SwissalpS/replacer/blob/7fdd94e9f1d8fa443d53129305555660297aae87/init.lua#L72

A time limit is not yet implemented.

**Comment by SwissalpS** [comment]
> A time limit is not yet implemented.

I don't intend to do so. The max_nodes setting was introduced precisely for this issue.

**Comment by HybridDog** [comment]
You could add a settingtypes.txt so that the settings can easily be adjusted in the advanced settings menu.

**Comment by SwissalpS** [comment]
> You could add a settingtypes.txt

[Thanks and done](https://github.com/SwissalpS/replacer/tree/dfbbf62d25a5b99fa09cc1efeeb089e17292dd5b)
