### ISSUE TITLE
what is causing crashes?

### ISSUE THREAD

**Issue by SwissalpS** [SwissalpS/replacer#16]
> Tried to replace a black scifi wall with a sliding door when server crashed

**Comment by SwissalpS** [comment]
maybe cable plates have the same issue (pointed thing above being same as bellow)

**Comment by HybridDog** [comment]
I think it is possible to set an (almost) arbitrary pointed thing above and under position with a modified minetest client, so mods should not make assumptions about these positions.

**Comment by SwissalpS** [comment]
trellis is also one that causes crashes, am putting it on blacklist for now.

**Comment by SwissalpS** [comment]
didn't have any more crashes, so I'm [guessing this fixed it.](https://github.com/SwissalpS/replacer/commit/38d250e625d812f860248ca73e77ebe31a94adc1)

Though I still feel this issue could be investigated further.
