### ISSUE TITLE
`get_entity_name()` is deprecated

### ISSUE THREAD

**Issue by OgelGames** [SwissalpS/replacer#24]
https://github.com/SwissalpS/replacer/blob/67eede24f3d505fcff62389a24b01d47c2bbb20f/inspect.lua#L79
https://github.com/minetest/minetest/blob/c940a57a384b1a75730776906451078d25c5aa52/doc/lua_api.txt#L6258

**Comment by SwissalpS** [comment]
@OgelGames thanks for pointing that out. I'll take a look at alternative options.

**Comment by SwissalpS** [comment]
[this should work](https://github.com/SwissalpS/replacer/pull/26)
