### ISSUE TITLE
Make inspector check and return mob protection and owner data

### ISSUE THREAD

**Issue by S-S-X** [SwissalpS/replacer#27]
Inspector reports some info about entities but not much, it would be useful if it would return owner and protection information for mobs if those are available.

That would allow me to make decision between life and death lot faster and also without having to squeeze poor animals into tubes for closer inspection.

This is important, some chickens already died because of this missing feature. Could have survived if it would be easy to inspect their loyalty and protection but as it takes too much time to check if escaped chicken was protected it was easier to just butcher and eat those.

**Comment by SwissalpS** [comment]
191ef5bf8adb404ea3393da46ac0bfbe56416829 should add what you want :)

Although, for the chickens sake, I should have made it return true no matter what, as that saves their lives :D

(I'm leaving this open in case insection tool now gives too much information, we can use this thread)

**Comment by SwissalpS** [comment]
I feel this was dealt with in https://github.com/SwissalpS/replacer/commit/fbc406f9cd49b8a1f9c7eaa733b808e3f10bc9e8

@S-S-X if not, please re-open
