### ISSUE TITLE
warnings when loading

### ISSUE THREAD

**Issue by OgelGames** [SwissalpS/replacer#39]
I noticed these two warnings in the debug when I loaded up the pandorabox mods:
```
2022-02-07 12:41:56: WARNING[Main]: [replacer] register_craft_method invalid arguments given.
2022-02-07 12:41:56: WARNING[Main]: [replacer] register_craft_method invalid arguments given.
```
I added a line to print the `uid` and `machine_itemstring` to find what they were from, which was `vines` and `wine`.

The problem is that there is no optional dependency on these mods, which get loaded after `replacer`.

**Comment by SwissalpS** [comment]
thanks, good catch :)
I've been checking too well in this case. I prefer not to have a huge optional_depndencies list.
