### ISSUE TITLE
`hud_add()` can fail and return a nil, resulting in crash on next `hud_get()` call

### ISSUE THREAD

**Issue by yl-whosit** [SwissalpS/replacer#52]
According to the API:
```
hud_add(hud definition): add a HUD element described by HUD def, returns ID number on success
```

(our internal ref 6502)

**Comment by SwissalpS** [comment]
> 
> (our internal ref 6502)

Where can I see that?
So you have cases where ``hud_add`` actually fails?

**Comment by yl-whosit** [comment]
Had a couple of crashes like this:
```
ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod '' in callback item_OnPlace(): ../mods/rhotator/notify.lua:120: bad argument #1 to 'hud_get' (number expected, got nil)
ERROR[Main]: stack traceback:
ERROR[Main]: [C]: in function 'hud_get'
ERROR[Main]: ../mods/rhotator/notify.lua:120: in function 'notify'
ERROR[Main]: ../mods/rhotator/init.lua:690: in function 'copy_rotation_callback'
ERROR[Main]: ../mods/rhotator/init.lua:485: in function 'func'
ERROR[Main]: ../builtin/profiler/instrumentation.lua:108: in function 'callback'
ERROR[Main]: ../builtin/game/item.lua:285: in function 'on_place'
ERROR[Main]: ../mods/replacer/replacer.lua:214: in function 'replace_single_node'
ERROR[Main]: ../mods/replacer/replacer.lua:307: in function <../mods/replacer/replacer.lua:252>
```

As I understand it, some *other* bugged mod can be creating too many huds and not removing them...

**Comment by yl-whosit** [comment]
Since replacer crashed twice and we didn't have other mods crashing like this, I'm starting to suspect it may be the replacer code somehow, but I don't see it...

**Comment by SwissalpS** [comment]
Thanks, I'll look into it. Can't hurt to include code that doesn't crash even in a very unlikely event.

**Comment by SwissalpS** [comment]
If you do figure out how to replicate it, I'd be grateful to be notified, for testing reasons.

**Comment by yl-whosit** [comment]
Wait, did I mix up rhotator and replacer?

**Comment by SwissalpS** [comment]
Now I'm confused. [replacer] has no HUD! I was thinking of [postool]

**Comment by yl-whosit** [comment]
Ok, so both crashes are from `rhotator`... and I was looking at the right code, I just filed it to a wrong repo...
Sorry. :/

**Comment by SwissalpS** [comment]
it's OK. Made me check [postool] and found that it doesn't check against nil everywhere.
