### ISSUE TITLE
Restore standalone singlemode replacer

### ISSUE THREAD

**Issue by S-S-X** [SwissalpS/replacer#9]
```xml
<SX> I still think that replacer should be restored
<SX> ... as upgradeable tool that new players without much machinery and resourcer can also use
<a> +1
<SX> single mode replacer is very useful if you want to make better than cobble hut without much resources
<SwissalpS> I thought it made it very easy for newbs that knew about it. I tested with other
account, could skip all the pickaxes and go straight to diamond tools with it
<a> Maybe add back the single-node-only replacer as cheaper than the current one, but nerf it to 
an iron ingot in the middle instead of a stick?
<SX> that's true it can be used for mining but it has not happened much there
<SX> *here
<SwissalpS> every tool we add, slows us down a little every time we open inventory ....
<SwissalpS> ... I like the idea too, with the upgrade, maybe we would use the blocky-world
recipe if we do it though
<a> If that's a problem, why not remove the bike mod?
<SwissalpS> think it was HybridDog that introduced that rec.
<SX> I think recipe could be more expensive and remember that for efficient mining with replacer one also needs nodes used as replacement
<SwissalpS> it's much easier to add than to remove items
<SwissalpS> I used canned goods as replacement, they drop and can be collected with tubes
<SwissalpS> those tests where before it was a technic tool, so I still got XP doing it
<SX> yes and that usually already requires very specific equipment and some resources, we're not talking about new player anymore
<SwissalpS> well noobs wouldn't know but newbs can easily be savy enough
<SX> basically when you have that stuff you also are able to mine with digtron which is faster than replacer and allows bringing more back
<a> Just nerf the recipe to use an iron ingot so they have to get pickaxes before replacer
<SX> iron or even copper, gold ingot
<xercyst> i guess middle can be blank, or workshop or something
<SX> but should be able to get before building technic machines
<SX> I see it as very imortant tool to improve buildings we see around
<SwissalpS> yes, that's why I initialy kept the cheap rec. when merging HybridDogs version
<SX> I've seen huge change when players are able to build rotated nodes without screwdriver, screwdriver just screws you when it breaks and you will stop using those nodes and go back to cobble hut
<SwissalpS> which is: chest | obsidian | obsidian | obs | stick | obs | obs | obs | chest
<warmalcat> other ppl can get into the regular golden chest right?
<a> Obsidian is cheap?
<a> warmalcat: Yes
<SwissalpS> for starter not so easy
<a> I very much agree with SX
<SwissalpS> unless use admin shop oc
<SwissalpS> yes, SX you should put those arguments on github (preferably the active repo)
<SX> for anyone not so easy before they get to asteroids, at that point they've stack of bigtrons and quarries
```

I'll try to improve formatting later... edit. actually formatting is good enough :)

**Comment by SwissalpS** [comment]
in summary:
base tool: cheap rec.

technic tool rec. includes base tool and crystal

Pros:
- give low level designers a tool to motivate nice builds
- give higher level players an alternative to digtron / drill
- give higher level players a tool to become designers because they can try out different materials with one click

Cons:
- yet another tool to load
- ? err skipped my mind @coil0 what was it again?

**Comment by S-S-X** [comment]
Add recipe that is cheap enough that materials can be obtained without technic tools but expensive enough so it wont be first tool that can be made.

Using replacer should not give any XP to user.

I'd say good recipe could maybe use one default:gold_ingot, default:diamond, default:pick_mese and default:brick_block
That requires basically finding 5 different materials: gold, diamond, mese, wood and clay.

**Comment by SwissalpS** [comment]
maybe spade instead of pickaxe?

**Comment by S-S-X** [comment]
> <coil> Even the basic replacer is more powerful than any pickaxe

Replacer is more powerful only because it does not require repairing.
Suggestion: also add some tool wear to basic replacer.

**Comment by BobFred7** [comment]
> I'd say good recipe could maybe use one default:gold_ingot, default:diamond, default:pick_mese and default:brick_block
> That requires basically finding 5 different materials: gold, diamond, mese, wood and clay.
> 
> Everything can be obtained from earth, is included in default minetest game and still requires some effort to get all of this.

Wood and clay can be gathered without tools, and gold, diamond, and mese can be obtained without a pickaxe through the admin store. The basic replacer can still be the first tool. We need to pick materials that are in MTG, can be found on earth, aren't too uncommon, and require tools to get.

**Comment by SwissalpS** [comment]
currently I'm working on smth like this:
		{'default:chest', 'default:gold_ingot', ''},
		{'', 'default:mese_crystal_fragment', ''},
		{'', 'default:steel_ingot', 'default:chest'},
the admin-shop makes almost any ore available without the need for pickaxe.

**Comment by BobFred7** [comment]
Seems fine, I guess

**Comment by SwissalpS** [comment]
I'm open to suggestions. Felt SX's idea is good but just a bit on the expensive side. I understand why diamond should be in there, but as BobFred7 mentioned, can be had from admin-shop without digging.
Maybe I'll feel different about it tomorrow again :)

**Comment by S-S-X** [comment]
Yea, I added default:brick_block just because of that, yes it can be obtained without tools and it is really cheap but you cant obtain it from spawn or from closest field / forest and also you need to do some smelting and crafting
It requires you to do something: either find shop selling those or go swim and then smelt+craft stuff you obtained.

**Comment by SwissalpS** [comment]
@thomasrudin there will be an issue where we need admins help. The current tool is replacer:replacer,
after this, replacer:replacer will be the base tool for backward compat. and replacer:replacer_technic will be the upgraded tool.
So a couple of replacers will downgrade and we need to provide upgraded ones for those players who crafted by the current technic-recipe.

**Comment by thomasrudin** [comment]
>  So a couple of replacers will downgrade and we need to provide upgraded ones for those players who crafted by the current technic-recipe.

Sure thing, i'll prepare a full chest of them in the moderator area (accessible via travelnet owner: "admin", network: "moderator")

**Comment by SwissalpS** [comment]
[my branch upgradable](https://github.com/SwissalpS/replacer/tree/upgradable) is ready for beta-testers.
I've included a recipe for directly crafting the technic version. Maybe we drop that.
Also I'm open for discussion on the base-recipe and anything really ;)

**Comment by thomasrudin** [comment]
> technic mod is optional

Nice, now i can use the latest version on non-technic servers too :+1:  (https://github.com/damocles-minetest/damocles-mods/pull/106)

**Comment by SwissalpS** [comment]
I feel there should be a solution to not need multiple tools for the upgrade. Just a meta entry that marks a tool as upgraded. But I don't want to have to watch for every craft to do so.

**Comment by SwissalpS** [comment]
[merge candidate is now this branch](https://github.com/SwissalpS/replacer/tree/doAsMuchAsPossible)
It fixes #10 by doing as much as possible before aborting instead of just telling user that too many nodes have been detected.

**Comment by SwissalpS** [comment]
If nobody finds any issues or wants recipe changes, [this is ready to merge to master](https://github.com/SwissalpS/replacer/tree/e56b579186de56c0db925ac08fe60624e32432cf)

**Comment by thomasrudin** [comment]
> If nobody finds any issues or wants recipe changes, this is ready to merge to master

LGTM (haven't tested it though)
